#!/bin/bash

## Uncomment to build the Docker image
# Make sure you have Docker installed and running
# If you want to build the image, run this command in the terminal:
#docker build -t oumarkme/vviewer .

## RUN THIS COMMAND TO START THE CONTAINER
docker run --name vviewer -p 9876:9876 -v $(pwd)/data:/data --rm -m 1g --cpus 4 oumarkme/vviewer
